# Generated by Django 6.1.1 on 2026-10-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=90000)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.CharField(max_length=3000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('category', models.CharField(choices=[('politics', 'Politics'), ('economy', 'Economy'), ('society', 'Society'), ('world', 'World'), ('op-ed', 'OP-ED'), ('sports', 'Sports'), ('diaspora', 'Diaspora'), ('market', 'Market')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
        ),
    ]
