# Generated by Django 6.1.1 on 2026-09-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'title',
                    models.TextField(max_length=1500)
                ),
                (
                    'description',
                    models.TextField(max_length=9000)
                ),
                (
                    'image',
                    models.ImageField(upload_to='blog_images/')
                ),
                (
                    'content',
                    models.TextField(max_length=30000000)
                ),
                (
                    'created_date',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'updated_date',
                    models.DateTimeField(auto_now=True)
                ),
                (
                    'likes',
                    models.PositiveIntegerField(default=0)
                ),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(max_length=300)
                ),
                (
                    'email',
                    models.EmailField(max_length=254)
                ),
                (
                    'body',
                    models.TextField()
                ),
                (
                    'created_date',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'posts',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='blog.blog'
                    )
                ),
            ],
        ),
    ]
