# Generated by Django 6.1.1 on 2026-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_content_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=1500),
        ),
    ]
