# Generated by Django 6.1.1 on 2026-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_content_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('economy', 'Economy'), ('society', 'Society'), ('world', 'World'), ('op-ed', 'OP-ED'), ('sports', 'Sports'), ('diaspora', 'Diaspora'), ('market', 'Market')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
