# Generated by Django 6.1.1 on 2026-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergedDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('colm_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('source_file_count', models.PositiveIntegerField(default=0)),
                ('merged_file', models.FileField(upload_to='merged/')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
